pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    
    environment {

        cluster = "production"
        service = "prodsvc"
    }

    
        stage("deploy to Production clustor ECS") {
            steps{
                withAWS(credentials: 'awscreds', region: 'ap-south-1') {
			sh 'aws ecs update-service --cluster ${cluster}  --service ${service} --force-new-deployment'
			
                }
            }
} 
}
}
