pipeline {
    agent any
    
    environment {
        
        vprofileRegistry = "http://574468706409.dkr.ecr.ap-south-1.amazonaws.com"
        cluster = "production"
        service = "prodsvc"
    }

    stages {
        stage("deploy to Production Cluster ECS") {
            steps {
                withAWS(credentials: 'awscreds', region: 'ap-south-1') {
			sh 'aws ecs update-service --cluster ${cluster}  --service ${service} --force-new-deployment'
			
                }
            }
} 
}
}
